const pieces = {
    "KICK":            {'path': "/img/drumPieces/Kick.jpg"}, 
    "SNARE":           {'path': "/img/drumPieces/Snare.jpg"}, 
    "TOM":             {'path': "/img/drumPieces/Tom.jpg"}, 
    "FLOOR_TOM":       {'path': "/img/drumPieces/FloorTom.jpg"},
    "RIDE":            {'path': "/img/drumPieces/Ride.jpg"},
    "CRASH":           {'path': "/img/drumPieces/Crash.jpg"},
    "SPLASH":          {'path': "/img/drumPieces/Splash.jpg"},
    "CHINA":           {'path': "/img/drumPieces/China.jpg"},
    "PERCUSSION":      {'path': "/img/drumPieces/Percussion.jpg"},
    "PAD":             {'path': "/img/drumPieces/Pad.jpg"},
    "HIHAT_OPEN":      {'path': "/img/drumPieces/Blank.jpg"},
    "HIHAT_CLOSED":    {'path': "/img/drumPieces/Blank.jpg"},
    "HIHAT_PEDAL":     {'path': "/img/drumPieces/Blank.jpg"},
    "HIHAT_CC":        {'path': "/img/drumPieces/Blank.jpg"},
    "HIHAT":           {'path': "/img/drumPieces/Blank.jpg"},
    "CYMBAL":          {'path': "/img/drumPieces/Blank.jpg"},
}